# Generated by Django 3.2.9 on 2021-11-14 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=30)),
                ('editorial', models.CharField(max_length=60)),
                ('numpags', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=200, null=True)),
                ('fechaPrestamo', models.DateTimeField(auto_now=True)),
                ('fechaDevolucion', models.DateTimeField(null=True)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.libro')),
            ],
        ),
    ]
