# Generated by Django 3.2.6 on 2021-09-18 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=300)),
                ('Dni', models.IntegerField()),
                ('Telefono', models.IntegerField()),
                ('direccion', models.TextField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Fecha de Nacimiento', models.DateTimeField()),
                ('Fecha de Publicacion', models.DateTimeField()),
            ],
        ),
    ]
